name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Checkout libxposed-api
        uses: actions/checkout@v4
        with:
          repository: s1204IT/libxposed-api
          ref: master
          path: libxposed/api
          fetch-depth: 0

      - name: Build dependencies
        working-directory: libxposed/api
        run: |
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8' >> gradle.properties
          ./gradlew publishToMavenLocal --no-daemon
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

      - name: Build with Gradle
        run: |
          {
            echo 'org.gradle.caching=true'
            echo 'org.gradle.parallel=true'
            echo 'org.gradle.vfs.watch=true'
            echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8'
          } >> gradle.properties
          ./gradlew publishToMavenLocal --no-daemon
          {
            echo "version=$(cat helper-ktx/build.gradle.kts | grep version | awk -F\" '{print $2}')"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
          } >> $GITHUB_ENV
          rm -rf ~/.m2/repository/io/github/libxposed/api/
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

      - name: Upload maven library
        uses: actions/upload-artifact@v4
        with:
          name: libxposed-helper-${{ env.version }}@${{ env.commit }}
          path: ~/.m2/repository/

      - name: Prepare pages
        run: |
          mkdir -p docs/ktx
          cp -r helper/build/intermediates/java_doc_dir/release/javaDocReleaseGeneration/* docs/
          cp -r helper-ktx/build/intermediates/java_doc_dir/release/javaDocReleaseGeneration/* docs/ktx/

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
